
server:
  port: 3000

logging:
  level:
    org.springframework.web: DEBUG
    com.djava.meetingRoom: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meetingRoom?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQLDialect