server:
  port: 8081

logging:
  level:
    org.springframework.web: DEBUG
    com.djava.meetingRoom: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservemeetingroom?createDatabaseIfNotExist=true
    username: root
    password: mysql"123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
